### ISSUE TITLE
Install fail on Fedora

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#111]
I have install uCoin on Fedora 22, 64 bits with:
```bash
dnf install node npm node-gyp
```
Logs:
```bash
[root@uCoin-fedora ~]# npm install -g ucoin
 
> naclb@0.0.1 install /usr/lib/node_modules/ucoin/node_modules/naclb
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ucoin/node_modules/naclb/.node-gyp"
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:72:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:75:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:83:16
gyp ERR! stack     at Object.oncomplete (fs.js:108:15)
gyp ERR! System Linux 4.0.4-301.fc22.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ucoin/node_modules/naclb
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
 
> netroute@0.2.5 install /usr/lib/node_modules/ucoin/node_modules/nat-upnp/node_modules/netroute
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ucoin/node_modules/nat-upnp/node_modules/netroute/.node-gyp"
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:72:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:75:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:83:16
gyp ERR! stack     at Object.oncomplete (fs.js:108:15)
gyp ERR! System Linux 4.0.4-301.fc22.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ucoin/node_modules/nat-upnp/node_modules/netroute
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

> usage@0.6.0 install /usr/lib/node_modules/ucoin/node_modules/usage
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ucoin/node_modules/usage/.node-gyp"
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:72:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:75:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:83:16
gyp ERR! stack     at Object.oncomplete (fs.js:108:15)
gyp ERR! System Linux 4.0.4-301.fc22.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ucoin/node_modules/usage
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

> ws@0.5.0 install /usr/lib/node_modules/ucoin/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> ws@0.4.31 install /usr/lib/node_modules/ucoin/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> scrypt@3.0.1 install /usr/lib/node_modules/ucoin/node_modules/scrypt
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ucoin/node_modules/scrypt/.node-gyp"
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:72:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:75:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:83:16
gyp ERR! stack     at Object.oncomplete (fs.js:108:15)
gyp ERR! System Linux 4.0.4-301.fc22.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ucoin/node_modules/scrypt
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

> vucoin@0.23.9 postinstall /usr/lib/node_modules/ucoin/node_modules/vucoin
> ./postinstall.sh

npm ERR! Linux 4.0.4-301.fc22.x86_64
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "ucoin"
npm ERR! node v0.10.36
npm ERR! npm  v2.11.1
npm ERR! code ELIFECYCLE

npm ERR! naclb@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the naclb@0.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the naclb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls naclb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```
Surely an issue with the [biding of Nacl](https://github.com/c-geek/naclb).

**Comment by c-geek** [comment]
Have you retried since ucoin@0.11.11 ?

**Comment by M5oul** [comment]
Nope, I will.

**Comment by M5oul** [comment]
I have retried with ucoin 0.11.11.

I get thoses errors:
```bash
npm install -g ucoin
 
> naclb@0.2.2 install /usr/lib/node_modules/ucoin/node_modules/naclb
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ucoin/node_modules/naclb/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: node-v0.10.36.tar.gz local checksum abcfad58340ae82b671e5d6d0e59377ae9242c0c36ecfab9de6d11e1e3bf8876 not match remote b9d7d1d0294bce46686b13a05da6fc5b1e7743b597544aa888e8e64a9f178c81
gyp ERR! stack     at deref (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:307:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:348:13)
gyp ERR! stack     at IncomingMessage.emit (events.js:117:20)
gyp ERR! stack     at _stream_readable.js:944:16
gyp ERR! stack     at process._tickCallback (node.js:442:13)
gyp ERR! System Linux 4.0.4-301.fc22.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ucoin/node_modules/naclb
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

> usage@0.6.0 install /usr/lib/node_modules/ucoin/node_modules/usage
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ucoin/node_modules/usage/.node-gyp"
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:72:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:75:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:83:16
gyp ERR! stack     at Object.oncomplete (fs.js:108:15)
gyp ERR! System Linux 4.0.4-301.fc22.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ucoin/node_modules/usage
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

> netroute@0.2.5 install /usr/lib/node_modules/ucoin/node_modules/nat-upnp/node_modules/netroute
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ucoin/node_modules/nat-upnp/node_modules/netroute/.node-gyp"
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:72:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:75:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:83:16
gyp ERR! stack     at Object.oncomplete (fs.js:108:15)
gyp ERR! System Linux 4.0.4-301.fc22.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ucoin/node_modules/nat-upnp/node_modules/netroute
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

> naclb@0.2.1 install /usr/lib/node_modules/ucoin/node_modules/vucoin/node_modules/naclb
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ucoin/node_modules/vucoin/node_modules/naclb/.node-gyp"
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:72:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:75:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:83:16
gyp ERR! stack     at Object.oncomplete (fs.js:108:15)
gyp ERR! System Linux 4.0.4-301.fc22.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ucoin/node_modules/vucoin/node_modules/naclb
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

> ws@0.5.0 install /usr/lib/node_modules/ucoin/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> ws@0.4.31 install /usr/lib/node_modules/ucoin/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> scrypt@4.0.7 install /usr/lib/node_modules/ucoin/node_modules/scrypt
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ucoin/node_modules/scrypt/.node-gyp"
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:72:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:75:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:83:16
gyp ERR! stack     at Object.oncomplete (fs.js:108:15)
gyp ERR! System Linux 4.0.4-301.fc22.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ucoin/node_modules/scrypt
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 4.0.4-301.fc22.x86_64
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "ucoin"
npm ERR! node v0.10.36
npm ERR! npm  v2.12.0
npm ERR! code ELIFECYCLE

npm ERR! naclb@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the naclb@0.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the naclb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls naclb
npm ERR! There is likely additional logging output above.

> vucoin@0.25.0 postuninstall /usr/lib/node_modules/ucoin/node_modules/vucoin
> ./postuninstall.sh

Remove bash completion script...

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```
