### ISSUE TITLE
Error when launching uCoin on Node 0.12

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#119]
```bash
# ucoind 
/usr/local/lib/node_modules/ucoin/node_modules/nat-upnp/node_modules/netroute/node_modules/bindings/bindings.js:79
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/usr/local/lib/node_modules/ucoin/node_modules/nat-upnp/node_modules/netroute/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/ucoin/node_modules/nat-upnp/node_modules/netroute/lib/netroute.js:3:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by c-geek** [comment]
I do not reproduce it. Ensure yourself you have both installed & launched ucoin with node 0.12, and not just run or install with 0.12 and launch with another version, or anything similar.

**Comment by c-geek** [comment]
OK, reproduced. Dunno yet how to solve it.

**Comment by c-geek** [comment]
No more exists, we use node@0.12 in production.
