### ISSUE TITLE
Error with every commands

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#186]
I have installed nodejs 0.12.7 and ucoin at it's last version on my ARM board, I get this error with every commands:
```bash
ucoind --help
/usr/local/lib/node_modules/ucoin/node_modules/nat-upnp/node_modules/netroute/node_modules/bindings/bindings.js:79
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/usr/local/lib/node_modules/ucoin/node_modules/nat-upnp/node_modules/netroute/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/ucoin/node_modules/nat-upnp/node_modules/netroute/lib/netroute.js:3:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by c-geek** [comment]
If you installed ucoin through `npm install -g ucoin`, then you have ucoin@0.11.3 which is not compliant with node@0.12.7.

Only *master* is compliant with this version of node.

**Comment by M5oul** [comment]
I installed ucoin from git.

**Comment by c-geek** [comment]
Can you make a git-log to see your latest commit please?

**Comment by M5oul** [comment]
```bash
commit 6e8ab7b1be9e8e1558d85d39e351927f74fce762
Author: cgeek <cem.moreau@gmail.com>
Date:   Mon Oct 12 20:54:35 2015 +0200

    Fix #141 increase sync timeout

commit 9706992e110d872a6c7b06b6066c4b7962d89fcf
Author: cgeek <cem.moreau@gmail.com>
Date:   Mon Oct 12 20:52:55 2015 +0200
```

**Comment by c-geek** [comment]
Try to reinstall the local modules with `npm install` into `ucoin` directory.

**Comment by M5oul** [comment]
Nope, it's this one:
```bash
commit 99cadfdc830f24f3d36e73bdad241c7661407010
Author: cgeek <cem.moreau@gmail.com>
Date:   Wed Oct 14 22:40:07 2015 +0200

    Fix: can enable http logs again

commit 197c476b475a9621c0a01ff5046570d20b9b1841
Author: cgeek <cem.moreau@gmail.com>
Date:   Wed Oct 14 22:28:17 2015 +0200
```

**Comment by M5oul** [comment]
I installed ucoin like this:
```bash
git clone https://github.com/ucoin-io/ucoin /tmp/ucoin
cd /tmp/ucoin/
npm install .
```

**Comment by c-geek** [comment]
Do you launch your ucoin commands with `ucoind` or with `bin/ucoind` inside `ucoin` folder?

**Comment by c-geek** [comment]
Also, with master branch, you will have to launch ucoin with extra node options:

    $ node --harmony /tmp/ucoin/bin/ucoind start

**Comment by M5oul** [comment]
Ok, it work :smile: 
Thank you.

**Comment by c-geek** [comment]
Cool :smile:
