### ISSUE TITLE
--autoconfig then add extra configuration cause an issue

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#187]
I autoconfig my node:
```bash
node --harmony bin/ucoind init --autoconf
```
Btw, It does very well configuration on my local node :smiling_imp:
I could see a great `conf.json` file.
Then, I add extra configuration:
```bash
node --harmony bin/ucoind config --remoteh moul.re
[2015-10-15 11:23:09.923] [ERROR] ucoind - [TypeError: undefined is not a function]
TypeError: undefined is not a function
    at /root/ucoin/bin/ucoind:369:15
    at /root/ucoin/bin/ucoind:740:18
    at _fulfilled (/root/ucoin/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/root/ucoin/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/root/ucoin/node_modules/q/q.js:756:13)
    at /root/ucoin/node_modules/q/q.js:564:44
    at flush (/root/ucoin/node_modules/q/q.js:110:17)
    at process._tickCallback (node.js:355:11)
```
It fail and `conf.json` file is empty :skull:
I have also try with `--salt` option.

It happen same stuff after `wizard key` and `config --remoteh` commands.

**Comment by M5oul** [comment]
Seems fixed. Thanks.
