### ISSUE TITLE
Issue to sync

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#188]
```bash
node --harmony bin/ucoind config sync metab.ucoin.io 9201
[2015-10-15 23:56:10.580] [ERROR] ucoind - [TypeError: Cannot read property 'saveConf' of undefined]
TypeError: Cannot read property 'saveConf' of undefined
    at /root/ucoin/bin/ucoind:362:22
    at /root/ucoin/bin/ucoind:740:18
    at _fulfilled (/root/ucoin/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/root/ucoin/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/root/ucoin/node_modules/q/q.js:756:13)
    at /root/ucoin/node_modules/q/q.js:564:44
    at flush (/root/ucoin/node_modules/q/q.js:110:17)
    at process._tickCallback (node.js:355:11)
```

**Comment by M5oul** [comment]
Seems to be fixed :smile:
