### ISSUE TITLE
Fail to build uCoin from git

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#200]
```bash
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_verify.o
  SOLINK_MODULE(target) Release/obj.target/scrypt.node
  COPY Release/scrypt.node
make: Leaving directory '/usr/lib/node_modules/ucoin/node_modules/scrypt/build'

> leveldown@1.4.1 install /usr/lib/node_modules/ucoin/node_modules/leveldown
> prebuild --download

prebuild WARN install EACCES, open '/root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.4.1-leveldown-v1.4.1-node-v14-linux-arm.tar.gz.4145-5f77a957.tmp'
prebuild ERR! build EACCES, mkdir '/root/.node-gyp/0.12.7/deps/http_parser'

> vucoin@0.25.1 postinstall /usr/lib/node_modules/ucoin/node_modules/vucoin
> ./postinstall.sh

npm ERR! Linux 4.0.4-cubietruck
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "."
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.4.1 install: `prebuild --download`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the leveldown@1.4.1 install script 'prebuild --download'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --download
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/ucoin/npm-debug.log
```

```bash
cat  /root/ucoin/npm-debug.log
35315 info postinstall scrypt@4.0.7
35316 verbose unlock done using /root/.npm/_locks/scrypt-396be0c9ae06002f.lock for /usr/lib/node_modules/ucoin/node_modules/scrypt
35317 info leveldown@1.4.1 Failed to exec install script
35318 verbose unsafe-perm in lifecycle false
35319 verbose unlock done using /root/.npm/_locks/leveldown-eabd1fee7db99daa.lock for /usr/lib/node_modules/ucoin/node_modules/leveldown
35320 verbose unlock done using /root/.npm/_locks/vucoin-8c3d39650059087b.lock for /usr/lib/node_modules/ucoin/node_modules/vucoin
35321 verbose about to build /usr/lib/node_modules/ucoin
35322 verbose unlock done using /root/.npm/_locks/ucoin-21722636080c1f9c.lock for /usr/lib/node_modules/ucoin
35323 verbose stack Error: leveldown@1.4.1 install: `prebuild --download`
35323 verbose stack Exit status 2
35323 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
35323 verbose stack     at EventEmitter.emit (events.js:110:17)
35323 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
35323 verbose stack     at ChildProcess.emit (events.js:110:17)
35323 verbose stack     at maybeClose (child_process.js:1015:16)
35323 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
35324 verbose pkgid leveldown@1.4.1
35325 verbose cwd /root/ucoin
35326 error Linux 4.0.4-cubietruck
35327 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "."
35328 error node v0.12.7
35329 error npm  v2.11.3
35330 error code ELIFECYCLE
35331 error leveldown@1.4.1 install: `prebuild --download`
35331 error Exit status 2
35332 error Failed at the leveldown@1.4.1 install script 'prebuild --download'.
35332 error This is most likely a problem with the leveldown package,
35332 error not with npm itself.
35332 error Tell the author that this fails on your system:
35332 error     prebuild --download
35332 error You can get their info via:
35332 error     npm owner ls leveldown
35332 error There is likely additional logging output above.
35333 verbose exit [ 1, true ]
35334 verbose unbuild lib/node_modules/ucoin/node_modules/leveldown
35335 info preuninstall leveldown@1.4.1
35336 info uninstall leveldown@1.4.1
35337 verbose unbuild rmStuff leveldown@1.4.1 from /usr/lib/node_modules
35338 verbose unbuild rmStuff in /usr/lib/node_modules/ucoin/node_modules
35339 info postuninstall leveldown@1.4.1
35340 silly gentlyRm /usr/lib/node_modules/ucoin/node_modules/leveldown is being purged from base /usr
35341 verbose gentlyRm don't care about contents; nuking /usr/lib/node_modules/ucoin/node_modules/leveldown
35342 silly vacuum-fs purging /usr/lib/node_modules/ucoin/node_modules/leveldown
35343 silly vacuum-fs quitting because other entries in /usr/lib/node_modules/ucoin/node_modules
35344 verbose unbuild lib/node_modules/ucoin
35345 info preuninstall ucoin@0.12.0
35346 info uninstall ucoin@0.12.0
35347 verbose unbuild rmStuff ucoin@0.12.0 from /usr/lib/node_modules
35348 silly gentlyRm /usr/bin/ucoind is being gently removed
35349 silly gentlyRm verifying /usr is an npm working directory
35350 silly gentlyRm containing path /usr is under npm's control, in /usr
35351 silly gentlyRm deletion target /usr/bin/ucoind is under /usr
35352 verbose gentlyRm vacuuming from /usr/bin/ucoind up to /usr
35353 info postuninstall ucoin@0.12.0
35354 silly gentlyRm /usr/lib/node_modules/ucoin is being purged from base /usr
35355 verbose gentlyRm don't care about contents; nuking /usr/lib/node_modules/ucoin
35356 silly vacuum-fs purging /usr/lib/node_modules/ucoin
35357 silly vacuum-fs quitting because other entries in /usr/lib/node_modules
```
It come from `leveldown` package.

**Comment by c-geek** [comment]
I will remove it then, since it is no more used.

**Comment by M5oul** [comment]
Great, it's fixed. Install went well.
