### ISSUE TITLE
Can't find lokijs & won't compute cause of root block needed

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#205]
After a `git pull` and `npm install -g .`, I try to sync, but ucoin told me it can't find `lokijs`:
```bash
# node --harmony bin/ucoind sync metab.ucoin.io 9201
module.js:338
    throw err;
          ^
Error: Cannot find module 'lokijs'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/ucoin/app/lib/sync.js:10:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by c-geek** [comment]
I will update the docs, as written in #173.

**Comment by c-geek** [comment]
N.B.: you should not use "npm install -g" with source code. Instead, you should rather do something like:

### Clone sources
```
$ git clone https://github.com/ucoin-io/ucoin.git ucoinsrc
$ cd ucoinsrc
```

### Use node v0.12

If you have [nvm](https://github.com/creationix/nvm):

```
$ nvm use 0.12
```

### Install uCoin modules

```
$ npm install
```

### Use uCoin

```
$ node --harmony bin/ucoind init --autoconf
$ node --harmony bin/ucoind sync twiced.fr 9201 --nocautious
$ node --harmony bin/ucoind start
```

**Comment by M5oul** [comment]
Thanks, installation and synchronization went very well :fast_forward: 
In cutecoin, my node is orange and I can't see what is the current block, on debug I get:
```bash
xFiHlyCSVSwCw==', 'status': 'UP', 'endpoints': ['BASIC_MERKLED_API 88.174.120.187 45001']}
DEBUG:node:refresh_block:Requesting connection info: moul.re:8999
DEBUG:__init__:requests_get:Request : http://moul.re:8999/blockchain/current
DEBUG:__init__:requests_get:Request : http://moul.re:8999/network/peering
DEBUG:__init__:requests_get:Request : http://moul.re:8999/wot/lookup/J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:__init__:requests_get:Request : http://moul.re:8999/network/peering/peers
DEBUG:__init__:requests_get:Request : http://moul.re:8999/node/summary
DEBUG:node:refresh_block:Error in block reply :  J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
DEBUG:node:refresh_block:status code != 200 => 404 ()
DEBUG:network_tab:refresh_nodes:Refresh nodes
DEBUG:community_view:refresh_status:Refresh status
```
[/blockchain/current](http://78.227.107.45:8999/blockchain/current) doesn't show anything.

My node need a root block to compute:
```bash
 node --harmony bin/ucoind start
[2015-11-06 17:32:59.328] [INFO] database - Loading...
[2015-11-06 17:33:05.717] [INFO] server - Node version: 0.12.0
[2015-11-06 17:33:05.728] [INFO] server - Node pubkey: J78bPUvLjxmjaEkdjxWLeENQtcfXm7iobqB49uT1Bgp3
[2015-11-06 17:33:05.739] [INFO] server - Starting core: fileDal
[2015-11-06 17:33:05.743] [INFO] server - Storing self peer...
[2015-11-06 17:33:05.828] [INFO] peering - External access: 78.227.107.45:8999
[2015-11-06 17:33:05.830] [DEBUG] peering - Generating server's peering entry...
[2015-11-06 17:33:06.025] [DEBUG] server - A more recent peering document is already recorded.
[2015-11-06 17:33:06.758] [WARN] peering - Peer record AWo9L89v3tUWbCnRRGrZ9Uwyy5Pb3EwgWfCgWgqLn2Re: A more recent peering document is already recorded.
[2015-11-06 17:33:06.766] [WARN] peering - Peer record HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk: A more recent peering document is already recorded.
[2015-11-06 17:33:08.695] [INFO] bma - uCoin server listening on 192.168.1.16 port 8999
[2015-11-06 17:33:08.719] [DEBUG] ucoind - Server ready!
[2015-11-06 17:33:08.760] [WARN] ucoin_default - Waiting for a root block before computing new blocks
[2015-11-06 17:33:08.795] [DEBUG] ucoin_default - Computing stats...
[2015-11-06 17:33:09.791] [INFO] ucoin_default - New document to send to 1 member and 1 non-member peers
[2015-11-06 17:33:09.814] [DEBUG] multicaster - --> new Peer to be sent to 2 peer(s)
[2015-11-06 17:33:09.828] [INFO] multicaster - POST peering J78bPUvLjx to peer HnFcSms8jz
[2015-11-06 17:33:09.850] [INFO] multicaster - POST peering J78bPUvLjx to peer AWo9L89v3t
[2015-11-06 17:33:11.186] [DEBUG] ucoin_default - Computing stats: done!
[2015-11-06 17:45:50.769] [DEBUG] server - Root block required first
[2015-11-06 17:45:50.772] [WARN] http - Root block required first
```
What do that mean? The first block is well here! An issue?

**Comment by c-geek** [comment]
@M5oul have you made another `init` between `sync` and `start`? This would explain why you don't have root block.

**Comment by M5oul** [comment]
Nope, I will try it :smile:

**Comment by c-geek** [comment]
No you should not! `init` completely resets both data & conf. I was just wondering if you did it, because it would explain why you don't have blocks :)

**Comment by M5oul** [comment]
ok

**Comment by M5oul** [comment]
I have try to `reset data` and `sync`. It seems, the issue about root block needed to compute is still here!

**Comment by c-geek** [comment]
I've made an update and I obviously have 3 working nodes.

Please try to:

```
$ cd ucoinsrc
$ git pull origin master
$ node --harmony bin/ucoind reset data
$ node --harmony bin/ucoind sync twiced.fr 9201 --nocautious
$ node --harmony bin/ucoind start
```

**Comment by M5oul** [comment]
Seems fixed!
