### ISSUE TITLE
My node is broken :(

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#207]
I think my node is broken. When I try to restart it:
```bash
PM2 App name:ucoin id:0 online
ucoin-0 [2015-11-10 19:53:51.169] [INFO] database - Loading...
ucoin-0 SyntaxError: Unexpected end of input
    at Object.parse (native)
    at LokiEventEmitter.Loki.loadJSON (/root/ucoin/node_modules/lokijs/src/lokijs.js:630:22)
    at loadDatabaseCallback (/root/ucoin/node_modules/lokijs/src/lokijs.js:897:18)
    at readFileCallback (/root/ucoin/node_modules/lokijs/src/lokijs.js:826:11)
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
PM2 App name:ucoin id:0 exited with code 255
PM2 Starting execution sequence in -fork mode- for app name:ucoin id:0
PM2 App name:ucoin id:0 online
ucoin-0 [2015-11-10 19:53:58.713] [INFO] database - Loading...
ucoin-0 SyntaxError: Unexpected end of input
    at Object.parse (native)
    at LokiEventEmitter.Loki.loadJSON (/root/ucoin/node_modules/lokijs/src/lokijs.js:630:22)
    at loadDatabaseCallback (/root/ucoin/node_modules/lokijs/src/lokijs.js:897:18)
    at readFileCallback (/root/ucoin/node_modules/lokijs/src/lokijs.js:826:11)
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
PM2 App name:ucoin id:0 exited with code 255
PM2 Starting execution sequence in -fork mode- for app name:ucoin id:0
PM2 App name:ucoin id:0 online
ucoin-0 [2015-11-10 19:54:06.207] [INFO] database - Loading...
ucoin-0 SyntaxError: Unexpected end of input
    at Object.parse (native)
    at LokiEventEmitter.Loki.loadJSON (/root/ucoin/node_modules/lokijs/src/lokijs.js:630:22)
    at loadDatabaseCallback (/root/ucoin/node_modules/lokijs/src/lokijs.js:897:18)
    at readFileCallback (/root/ucoin/node_modules/lokijs/src/lokijs.js:826:11)
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
PM2 App name:ucoin id:0 exited with code 255
PM2 Starting execution sequence in -fork mode- for app name:ucoin id:0
PM2 App name:ucoin id:0 online
```
```bash
PM2: 2015-11-10 19:53:44: App name:ucoin id:0 online
PM2: 2015-11-10 19:53:51: App name:ucoin id:0 exited with code 255
PM2: 2015-11-10 19:53:51: Starting execution sequence in -fork mode- for app name:ucoin id:0
PM2: 2015-11-10 19:53:51: App name:ucoin id:0 online
PM2: 2015-11-10 19:53:59: App name:ucoin id:0 exited with code 255
PM2: 2015-11-10 19:53:59: Starting execution sequence in -fork mode- for app name:ucoin id:0
PM2: 2015-11-10 19:53:59: App name:ucoin id:0 online
PM2: 2015-11-10 19:54:06: App name:ucoin id:0 exited with code 255
PM2: 2015-11-10 19:54:06: Starting execution sequence in -fork mode- for app name:ucoin id:0
PM2: 2015-11-10 19:54:06: App name:ucoin id:0 online
PM2: 2015-11-10 19:54:14: App name:ucoin id:0 exited with code 255
PM2: 2015-11-10 19:54:14: Starting execution sequence in -fork mode- for app name:ucoin id:0
PM2: 2015-11-10 19:54:14: App name:ucoin id:0 online
PM2: 2015-11-10 19:54:21: Stopping app:ucoin id:0
PM2: 2015-11-10 19:54:21: Process with pid 13337 still not killed, retrying...
PM2: 2015-11-10 19:54:21: Process with pid 13337 still not killed, retrying...
PM2: 2015-11-10 19:54:21: App name:ucoin id:0 exited with code 255
PM2: 2015-11-10 19:54:21: Process with pid 13337 killed
PM2: 2015-11-10 19:55:38: Starting execution sequence in -fork mode- for app name:ucoin id:0
PM2: 2015-11-10 19:55:38: App name:ucoin id:0 online

ucoin-0 (out): [2015-11-10 19:51:51.789] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:51:59.227] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:52:06.606] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:52:14.014] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:52:21.416] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:52:28.868] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:52:36.606] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:52:44.718] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:52:52.067] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:52:59.538] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:53:06.862] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:53:14.245] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:53:21.618] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:53:29.075] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:53:36.453] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:53:43.827] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:53:51.169] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:53:58.713] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:54:06.207] [INFO] database - Loading...
ucoin-0 (out): [2015-11-10 19:54:13.566] [INFO] database - Loading...

ucoin-0 (err):     at fs.js:334:14
ucoin-0 (err):     at FSReqWrap.oncomplete (fs.js:95:15)
ucoin-0 (err): SyntaxError: Unexpected end of input
ucoin-0 (err):     at Object.parse (native)
ucoin-0 (err):     at LokiEventEmitter.Loki.loadJSON (/root/ucoin/node_modules/lokijs/src/lokijs.js:630:22)
ucoin-0 (err):     at loadDatabaseCallback (/root/ucoin/node_modules/lokijs/src/lokijs.js:897:18)
ucoin-0 (err):     at readFileCallback (/root/ucoin/node_modules/lokijs/src/lokijs.js:826:11)
ucoin-0 (err):     at fs.js:334:14
ucoin-0 (err):     at FSReqWrap.oncomplete (fs.js:95:15)
ucoin-0 (err): SyntaxError: Unexpected end of input
ucoin-0 (err):     at Object.parse (native)
ucoin-0 (err):     at LokiEventEmitter.Loki.loadJSON (/root/ucoin/node_modules/lokijs/src/lokijs.js:630:22)
ucoin-0 (err):     at loadDatabaseCallback (/root/ucoin/node_modules/lokijs/src/lokijs.js:897:18)
ucoin-0 (err):     at readFileCallback (/root/ucoin/node_modules/lokijs/src/lokijs.js:826:11)
ucoin-0 (err):     at fs.js:334:14
ucoin-0 (err):     at FSReqWrap.oncomplete (fs.js:95:15)
ucoin-0 (err): TypeError: Cannot read property 'needsSave' of null
ucoin-0 (err):     at process.<anonymous> (/root/ucoin/bin/ucoind:767:23)
ucoin-0 (err):     at process.emit (events.js:104:17)
ucoin-0 (err):     at Signal.wrap.onsignal (node.js:655:46)

[PM2] Streaming realtime logs for [all] processes 

ucoin-0 SyntaxError: Unexpected end of input
    at Object.parse (native)
    at LokiEventEmitter.Loki.loadJSON (/root/ucoin/node_modules/lokijs/src/lokijs.js:630:22)
    at loadDatabaseCallback (/root/ucoin/node_modules/lokijs/src/lokijs.js:897:18)
    at readFileCallback (/root/ucoin/node_modules/lokijs/src/lokijs.js:826:11)
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
PM2 App name:ucoin id:0 exited with code 255
PM2 Starting execution sequence in -fork mode- for app name:ucoin id:0
PM2 App name:ucoin id:0 online
^C
```

**Comment by c-geek** [comment]
Your memory database is corrupted, your node was probably killed while persisting the memory DB.

Could you tell me more about that?

**Comment by c-geek** [comment]
I should find a safer way to persist the DB.

**Comment by c-geek** [comment]
Closing it, replaced by #254.
