### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#209]
```bash
TypeError: Cannot read property 'medianTime' of null
at /root/ucoin/app/lib/globalValidator.js:249:93
at fn (/root/ucoin/node_modules/async/lib/async.js:579:34)
at Immediate._onImmediate (/root/ucoin/node_modules/async/lib/async.js:495:34)
at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by c-geek** [comment]
Linked to #217.
