### ISSUE TITLE
Sync fail

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#211]
```bash
node --harmony bin/ucoin sync moul.re 8999 --nocautious

Progress:

Download: [||||||              ] 34 %
Apply:    [||||||              ] 33 %

Status: Cannot read property 'UDTime' of null
All done.
TypeError: Cannot read property 'UDTime' of null
    at /root/ucoin/app/service/BlockchainService.js:1426:37
    at GeneratorFunctionPrototype.next (native)
    at onFulfilled (/root/ucoin/node_modules/co/index.js:65:19)
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
```

**Comment by c-geek** [comment]
Should be fixed now, sync is working.
