### ISSUE TITLE
Allow to specify data home directory

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#212]
With [YunoHost package](https://moul.re/repo/moul/ucoin_ynh/), no `~/.config/ucoin/ucoin_default/` repository are created. I search in `/root/` and on `/home/admin/`. This repository is not created. I am sure of it, as I get that error when launching the node:
```bash
root@ucoin:~# node --harmony /home/yunohost.app/ucoin/bin/ucoind 
module.js:338
    throw err;
          ^
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/yunohost.app/ucoin/node_modules/inquirer/lib/objects/separator.js:6:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```
I don't know which user is YunoHost using when installing apps, but, the repository to let uCoin works isn't created.

**Comment by M5oul** [comment]
It could be great if we could specify with an option the path to store database.
