### ISSUE TITLE
Crash at sync

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#214]
```bash
Progress:

Download: [                    ] 1 %
Apply:    [                    ] 0 %

Status: Cannot read property 'transactions' of null
All done.
TypeError: Cannot read property 'transactions' of null
    at /root/ucoin/app/lib/sync.js:225:12
    at /root/ucoin/app/lib/sync.js:125:100
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
```

**Comment by M5oul** [comment]
Seems fixed.
