### ISSUE TITLE
Revert branch crashes

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#235]
Error : 

```
[2015-11-27 08:02:57.615] [DEBUG] ucoin_default - SWITCH: get absolute #42501-0000C14963F60B30EDAF5DE3DB4F058E320D7E6D...
[2015-11-27 08:02:57.616] [DEBUG] ucoin_default - SWITCH: revert main chain to block #42501...
[2015-11-27 08:02:57.618] [DEBUG] ucoin_default - SWITCH: main chain current = #42501-0000C14963F60B30EDAF5DE3DB4F058E320D7E6D...
[2015-11-27 08:02:57.619] [DEBUG] ucoin_default - SWITCH: apply side chain #42666-00001B21FF2D3CB611E0004773942792DB20E22D...
[2015-11-27 08:02:57.620] [DEBUG] ucoin_default - SWITCH: apply side block #42502-0000F95AD70C437BB1DC371BBDB8B17475823498 -> #42501-0000C14963F60B30EDAF5DE3DB4F058E320D7E6D...
[2015-11-27 08:02:57.704] [WARN] ucoin_default - SWITCH: error This block cannot have UniversalDividend
[2015-11-27 08:02:57.705] [DEBUG] ucoin_default - SWITCH: get absolute #42500-000045BBC0C6C04EF2F5F538A11E360AE7251272...
[2015-11-27 08:02:57.706] [DEBUG] ucoin_default - SWITCH: main chain current = #42501-0000C14963F60B30EDAF5DE3DB4F058E320D7E6D...
[2015-11-27 08:02:57.707] [DEBUG] ucoin_default - SWITCH: main chain revert #42501-0000C14963F60B30EDAF5DE3DB4F058E320D7E6D...

[2015-11-27 07:59:59.194] [DEBUG] ucoin_default - Reverting block #42501...
[2015-11-27 07:59:59.199] [WARN] peering - [TypeError: Cannot read property 'number' of null]
TypeError: Cannot read property 'number' of null
    at /home/ucoin/ucoin/app/lib/dal/fileDALs/BlockDAL.js:181:47
    at GeneratorFunctionPrototype.next (native)
    at onFulfilled (/home/ucoin/ucoin/node_modules/co/index.js:65:19)
    at runMicrotasksCallback (node.js:337:7)

```

It tries to revert since it forked and discovered other branches on the network but it fails everytime on block 42501.

**Comment by c-geek** [comment]
Is your instance up-to-date? I advise you to use [Binary releases](https://github.com/ucoin-io/ucoin/wiki/Install-uCoin-node#linux-x64-binary) now, otherwise it is hard to know which version of source code you run.

Also, I see your fork window is `100`, so reverting might be stuck because of this.

The easier for me would be that you make a tarball of your uCoin data and depose it somewhere, like with:

```
$ tar cz ~/ucoin.inso.tar.gz ~/.config/ucoin/ucoin_default --exclude "conf.json"
```

You can also make a tarball with conf.json, but with please obfuscate your password/salt.

**Comment by Insoleet** [comment]
Here you go : 
https://moul.re/jirafeau/f.php?h=2tQDhSDG

To delete the archive : 
https://moul.re/jirafeau/f.php?h=2tQDhSDG&d=2e744

**Comment by c-geek** [comment]
Downloaded, thanks!

**Comment by c-geek** [comment]
OK, so ... several things to say.

First, I am sorry, but your node will have to be reseted since your initial sync led to incorrect blocks! What happened? Well, basically during sync uCoin used the default parameter for `dt`, which is a month, and applied this dt to all blocks with dividend it encountered. In other words, your node believes the first UD happened the 21th of February whereas it was the 22th of January. Your database is a mess now, and your node refuses to apply block [42502](http://metab.ucoin.io/blockchain/block/42502) which contains a UD, arguing this is not the correct moment for a UD :grin: 

Anyway, even if this problem wasn't here, uCoin had another bug which made your node stuck at block 42501: pulling of blocks was using a very bad algorithm, downloading blocks *from top of remote* nodes (for example, it was downloading blocks [43356 -> 42502]) instead of downloading them *from local current block* and *to top* of remote nodes ([42502 -> 42356]) which was making unnecessary long downloading process.

Anyway, this will be fixed in 0.12beta4 :smile:

**Comment by Insoleet** [comment]
Well I'm glad I helped you find such a weird bug beforewe get to more nodes ! :D why didn't it happen with Moul node ?

**Comment by c-geek** [comment]
Because the bug only occurs if you have wrong dt parameter in your conf.json file. Yet, Moul was using uCoin for a while and had good parameters in its conf.json, since previously I did register the good parameters as soon as I received root block, contrary to current version of the software.

Moul and I were immuned actually!
