### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#239]
```bash
./ucoin sync --nocautious moul.re 8999

Progress:

Download: [||||||||||||||||||||] 100 %
Apply:    [||||||||||||||||||| ] 98 %

Status: Cannot set property 'consumed' of undefined
All done.
TypeError: Cannot set property 'consumed' of undefined
    at SourcesDAL.getAvailableForPubkey.getUDSources.getSource.isAvailableSource.consumeSource (/home/moul/projects/ucoin-v0.12/app/lib/dal/fileDALs/SourcesDAL.js:73:18)
    at FileDAL.init.writeSideFileOfBlock.getAbsoluteBlockByNumberAndHash.getBlocksBetween.getWrittenIdtyByPubkey.getWrittenIdtyByUID.searchJustIdentities.isMemberAndNonLeaver.setConsumedSource (/home/moul/projects/ucoin-v0.12/app/lib/dal/fileDAL.js:674:28)
    at /home/moul/projects/ucoin-v0.12/app/lib/blockchainContext.js:592:21
    at iterate (/home/moul/projects/ucoin-v0.12/node_modules/async/lib/async.js:131:13)
    at /home/moul/projects/ucoin-v0.12/node_modules/async/lib/async.js:142:25
    at executeBound (/home/moul/projects/ucoin-v0.12/node_modules/underscore/underscore.js:701:67)
    at bound (/home/moul/projects/ucoin-v0.12/node_modules/underscore/underscore.js:733:14)
    at _fulfilled (/home/moul/projects/ucoin-v0.12/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/home/moul/projects/ucoin-v0.12/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/home/moul/projects/ucoin-v0.12/node_modules/q/q.js:756:13)
```
It happend a second time. I can't start my node on my desktop computer cause the conf file isn't fill (no money name writen).

**Comment by c-geek** [comment]
Confirmed.

**Comment by c-geek** [comment]
For an unknown reason, http://metab.ucoin.io/blockchain/blocks/500/42000 only returns the first 149 blocks.

However, http://metab.ucoin.io/blockchain/block/42160 exists. It is simply not returned by `/blockchain/blocks` URI.

**Comment by c-geek** [comment]
You should now be able to sync with `metab.ucoin.io 9201`.

Also, you could update your own node with DEV version (*master* branch). No resync with metab.ucoin.io needed, just update.

**Comment by M5oul** [comment]
I've ever done it. The issue is with [the binary](https://github.com/ucoin-io/ucoin/wiki/Install-uCoin-node#linux-x64-binary) that you should update.

**Comment by c-geek** [comment]
You mean *already*?

Yes I will release a 0.12beta4 tomorrow.

**Comment by M5oul** [comment]
I updated moul.re node.
I'm installing this binary on my desktop computer.
