### ISSUE TITLE
Failed build uCoin 0.13 with Node-js 4.2.3 on Debian 8

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#278]
I have try to build uCoin 0.13 branch with Node-js 4.2.3 on a fresh Debian Jessie, but it failed:
```bash
> node-gyp rebuild

make: Entering directory '/root/ucoin/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/root/ucoin/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'

> bufferutil@1.2.1 install /root/ucoin/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/root/ucoin/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/root/ucoin/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'

> vucoin@0.26.0 postinstall /root/ucoin/node_modules/vucoin
> ./postinstall.sh

‘./completion.sh’ -> ‘/etc/bash_completion.d/ucoin’

> usage@0.6.0 install /root/ucoin/node_modules/usage
> node-gyp rebuild

module.js:339
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:435:26)
    at node.js:578:27
    at doNTCallback0 (node.js:419:9)
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/ucoin/node_modules/usage
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! usage@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the usage@0.6.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the usage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls usage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/ucoin/npm-debug.log
root@debian-1gb-lon1-01:~/ucoin# node --version
v4.2.3
```

**Comment by c-geek** [comment]
I do not have such errors. Here is what I tried (Debian 8 Jessie x64):

```
$ su
# apt-get update
# apt-get install build-essential g++ git
# exit
$ wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
$ nvm install 4
```

Open a new terminal:

```
$ git clone https://github.com/ucoin-io/ucoin.git
$ cd ucoin
$ git checkout 0.13
$ nvm use 4
$ npm install
```

I do have a few compilation errors for `socket.io` but it is non-blocking.

**Comment by M5oul** [comment]
I follow your tutorial. I installed nvm, `node --version` gave me 4.x.x, but at `npm install` step:
```bash
root@debian-512mb-sgp1-01:~/ucoin# node --version
v4.2.4
root@debian-512mb-sgp1-01:~/ucoin# npm install
npm WARN package.json ucoin@0.12.10 license should be a valid SPDX license expression
npm WARN package.json Dependency 'sha1' exists in both dependencies and devDependencies, using 'sha1@1.1.0' from dependencies
npm WARN deprecated MD5@1.3.0: deprecated, use lowercase 'md5@2.x' from now on
 
> naclb@1.0.0 install /root/ucoin/node_modules/naclb
> node-gyp rebuild

make: Entering directory '/root/ucoin/node_modules/naclb/build'
  CXX(target) Release/obj.target/nacl/nacl.o
Killed
root@debian-512mb-sgp1-01:~/ucoin#   CXX(target) Release/obj.target/nacl/functions.o
../functions.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE sign(Nan::NAN_METHOD_ARGS_TYPE)’:
../functions.cc:82:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < smlen; i++) {
                     ^
  CXX(target) Release/obj.target/nacl/tweetnacl.o
../tweetnacl.cpp: In function ‘int vn(const u8*, const u8*, int)’:
../tweetnacl.cpp:4:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 #define FOR(i,n) for (i = 0;i < n;++i)
                               ^
../tweetnacl.cpp:61:5: note: in expansion of macro ‘FOR’
     FOR(i, n) d |= x[i] ^ y[i];
     ^
../tweetnacl.cpp: In function ‘int crypto_sign(u8*, u64*, const u8*, u64, const u8*)’:
../tweetnacl.cpp:4:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 #define FOR(i,n) for (i = 0;i < n;++i)
                               ^
../tweetnacl.cpp:840:5: note: in expansion of macro ‘FOR’
     FOR(i, n) {
     ^
../tweetnacl.cpp: In function ‘int crypto_sign_open(u8*, u64*, const u8*, u64, const u8*)’:
../tweetnacl.cpp:4:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 #define FOR(i,n) for (i = 0;i < n;++i)
                               ^
../tweetnacl.cpp:921:5: note: in expansion of macro ‘FOR’
     FOR(i, n) {
     ^
../tweetnacl.cpp:4:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 #define FOR(i,n) for (i = 0;i < n;++i)
                               ^
../tweetnacl.cpp:935:9: note: in expansion of macro ‘FOR’
         FOR(i, n) {
         ^
../tweetnacl.cpp:4:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 #define FOR(i,n) for (i = 0;i < n;++i)
                               ^
../tweetnacl.cpp:940:5: note: in expansion of macro ‘FOR’
     FOR(i, n) {
     ^
  CXX(target) Release/obj.target/nacl/randombytes.o
  SOLINK_MODULE(target) Release/obj.target/nacl.node
  COPY Release/nacl.node
make: Leaving directory '/root/ucoin/node_modules/naclb/build'
```
Things didn't ends normally.
I couldn't launch it:
```bash
root@debian-512mb-sgp1-01:~/ucoin# node --harmony bin/ucoind 
module.js:340
    throw err;
    ^

Error: Cannot find module './dist/rx.joinpatterns'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/root/ucoin/node_modules/inquirer/node_modules/rx/index.js:8:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```
I try to reinstalled it. I get unmet dependencies:
```bash
root@debian-512mb-sgp1-01:~/ucoin# npm install
npm WARN package.json ucoin@0.12.10 license should be a valid SPDX license expression
npm WARN package.json Dependency 'sha1' exists in both dependencies and devDependencies, using 'sha1@1.1.0' from dependencies
npm WARN engineStrict Per-package engineStrict (found in this package's package.json) 
npm WARN engineStrict won't be used in npm 3+. Use the config setting `engine-strict` instead.
npm WARN unmet dependency /root/ucoin/node_modules/pm2/node_modules/vizion requires async@'0.9.0' but will load
npm WARN unmet dependency /root/ucoin/node_modules/pm2/node_modules/async,
npm WARN unmet dependency which is version 1.5.0
npm WARN unmet dependency /root/ucoin/node_modules/pm2/node_modules/pm2-axon-rpc requires commander@'1.0.5' but will load
npm WARN unmet dependency /root/ucoin/node_modules/pm2/node_modules/commander,
npm WARN unmet dependency which is version 2.9.0
npm WARN unmet dependency /root/ucoin/node_modules/pm2/node_modules/pm2-deploy requires async@'1.4.2' but will load
npm WARN unmet dependency /root/ucoin/node_modules/pm2/node_modules/async,
npm WARN unmet dependency which is version 1.5.0
npm WARN unmet dependency /root/ucoin/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /root/ucoin/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.3.0
npm WARN unmet dependency /root/ucoin/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /root/ucoin/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
npm WARN unmet dependency /root/ucoin/node_modules/istanbul/node_modules/js-yaml requires esprima@'^2.6.0' but will load
npm WARN unmet dependency /root/ucoin/node_modules/istanbul/node_modules/esprima,
npm WARN unmet dependency which is version 2.5.0
npm WARN unmet dependency /root/ucoin/node_modules/istanbul/node_modules/escodegen/node_modules/optionator requires wordwrap@'~0.0.2' but will load
npm WARN unmet dependency /root/ucoin/node_modules/istanbul/node_modules/wordwrap,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /root/ucoin/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/engine.io-parser requires has-binary@'0.1.5' but will load
npm WARN unmet dependency /root/ucoin/node_modules/socket.io-client/node_modules/has-binary,
npm WARN unmet dependency which is version 0.1.6
npm WARN unmet dependency /root/ucoin/node_modules/request-promise/node_modules/request/node_modules/har-validator requires chalk@'^1.1.1' but will load
npm WARN unmet dependency /root/ucoin/node_modules/request-promise/node_modules/chalk,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /root/ucoin/node_modules/request-promise/node_modules/request/node_modules/har-validator requires commander@'^2.9.0' but will load
npm WARN unmet dependency /root/ucoin/node_modules/commander,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /root/ucoin/node_modules/request-promise/node_modules/request/node_modules/http-signature/node_modules/sshpk requires assert-plus@'>=0.2.0 <0.3.0' but will load
npm WARN unmet dependency /root/ucoin/node_modules/request-promise/node_modules/request/node_modules/http-signature/node_modules/assert-plus,
npm WARN unmet dependency which is version 0.1.5
```
```bash
root@debian-512mb-sgp1-01:~/ucoin# git branch
* 0.13
  master
```

**Comment by c-geek** [comment]
Maybe you should try as non-root user, and on a fresh Debian Jessie installation.

**Comment by c-geek** [comment]
Any news?

**Comment by M5oul** [comment]
Same issues as my previous comment with a non-root user on a fresh Debian Jessie.

**Comment by M5oul** [comment]
Install crashed because there is not enough memory on the DO (512 Mo).
It works well with 1 Go.

**Comment by c-geek** [comment]
Ouf! Thanks.
