### ISSUE TITLE
TypeError: Cannot read property 'medianTime' of null

### ISSUE THREAD

**Issue by Sylvain303** [ucoin-io/ucoin#282]
Today ucoin node failed:

~~~
[2015-12-23 17:39:25.899] [DEBUG] peering - Remote #45755 Local #45755
[2015-12-23 17:39:25.903] [DEBUG] ucoin_default - SWITCH: 1 branches...
[2015-12-23 17:39:25.904] [DEBUG] ucoin_default - SWITCH: 0 potential side chain
s...
[2015-12-23 17:39:26.020] [DEBUG] blockdal - Clean some blocks from memory to disk...
[2015-12-23 17:39:26.021] [DEBUG] blockdal - Lower block = 45323
[2015-12-23 17:39:26.028] [DEBUG] blockdal - LastUD in loki = 45720
[2015-12-23 17:39:26.029] [DEBUG] blockdal - Lower in loki = 45286
[2015-12-23 17:39:26.030] [DEBUG] blockdal - Dead blocks = 37
[2015-12-23 17:39:26.033] [DEBUG] blockdal - To store in files = 45286 to 45323
[2015-12-23 17:39:26.734] [DEBUG] blockdal - Lower in loki now = 45324
[2015-12-23 17:39:26.735] [DEBUG] blockdal - LastUD in loki = 45720
[2015-12-23 17:43:36.420] [INFO] ucoin_default - ⬇ IDTY 9bZEATXBGPUSsk8oAYi4KAChg3rHKwNt67hVdErbNGCW vincentux
[2015-12-23 17:43:36.423] [INFO] ucoin_default - ⬇ CERT HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk block#45756
/home/ucoin/ucoin/app/lib/globalValidator.js:249
hrowExpiration && res.current && res.current.medianTime > res.target.medianTim
                                                                    ^
TypeError: Cannot read property 'medianTime' of null
    at /home/ucoin/ucoin/app/lib/globalValidator.js:249:93
    at fn (/home/ucoin/ucoin/node_modules/async/lib/async.js:579:34)
    at Immediate._onImmediate (/home/ucoin/ucoin/node_modules/async/lib/async.js:495:34)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
~~~

Same here: http://paste.twiced.fr/yemuyofame.hs

**Comment by Insoleet** [comment]
Same bug here.
```
ucoin_default-0 (err):                                                                     ^
ucoin_default-0 (err): TypeError: Cannot read property 'medianTime' of null
ucoin_default-0 (err):     at /home/ucoin/.ucoin/app/lib/globalValidator.js:249:93
ucoin_default-0 (err):     at fn (/home/ucoin/.ucoin/node_modules/async/lib/async.js:579:34)
ucoin_default-0 (err):     at Immediate._onImmediate (/home/ucoin/.ucoin/node_modules/async/lib/async.js:495:34)
ucoin_default-0 (err):     at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Node crashed, I probably need to resync fully my node to get it running again.

**Comment by c-geek** [comment]
This bug occured when we received a certification based on an unknown block (because our local node is out of sync with the network).
