### ISSUE TITLE
Error : Source not available

### ISSUE THREAD

**Issue by sbDevGit** [ucoin-io/ucoin#286]
My ucoin logs :
```bash
ucoin_default-0 [2015-12-26 12:43:40.015] [ERROR] ucoin_default - Source 7NoTJK95DYPDMpoad9obDPqXFW5JEXxmz4cyg39j5goQ:T:45692:F50D25BFCCDB0C466F2CF395FD72DBCB36C87FDA:236470047225155 is not available

ucoin_default-0 [2015-12-26 12:43:40.025] [ERROR] ucoin_default - Source 7NoTJK95DYPDMpoad9obDPqXFW5JEXxmz4cyg39j5goQ:D:45508:0000DCBE0A640D70D6EB86FB795988EC3CAA1198:2739899613848797 is not available

ucoin_default-0 [2015-12-26 12:43:40.038] [ERROR] server - [Error: channel closed]
ucoin_default-0 Error: channel closed
ucoin_default-0     at ChildProcess.target.send (child_process.js:414:26)
ucoin_default-0     at /root/.ucoin/app/service/BlockchainService.js:1081:28
ucoin_default-0     at Function.promise (/root/.ucoin/node_modules/q/q.js:642:9)
ucoin_default-0     at BlockchainService.current.promoted.branches.branches.submitBlock.that.tryToFork.co.revertCurrentBlock.async.waterfall.co.then.prove (/root/.ucoin/app/service/BlockchainService.js:1065:14)

ucoin_default-0     at /root/.ucoin/app/service/BlockchainService.js:1236:19
ucoin_default-0     at GeneratorFunctionPrototype.next (native)
ucoin_default-0     at onFulfilled (/root/.ucoin/node_modules/co/index.js:65:19)
ucoin_default-0     at /root/.ucoin/node_modules/co/index.js:54:5
ucoin_default-0     at co (/root/.ucoin/node_modules/co/index.js:50:10)
ucoin_default-0     at BlockchainService.current.promoted.branches.branches.submitBlock.that.tryToFork.co.revertCurrentBlock.async.waterfall.co.then.makeNextBlock (/root/.ucoin/app/service/BlockchainService.js:1231:12)
```

**Comment by c-geek** [comment]
Fixed in 0.13, since sources are now removed when consumed, which avoid uCoin to try add them in the next block (which provoked this error).
