### ISSUE TITLE
Can't start or sync node

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#300]
On `sqlite` branch, I can display uCoin help, but, I can't sync or even start my node:
```sh
node bin/ucoind sync upyum.com 40138 --nointeractive
2016-01-08T07:46:35-05:00 - info: >> NODE STARTING
2016-01-08T07:46:35-05:00 - error:  Error: SyntaxError: Unexpected token ,
    at Error (native)
    at /root/ucoin/app/lib/dal/fileDAL.js:121:15
    at process._tickCallback (node.js:368:9)
```

I think my conf is well set.

**Comment by M5oul** [comment]
It's ok since [that commit](https://github.com/ucoin-io/ucoin/commit/d165604f5dd20e92389bf148c9afd3a442520801).
