### ISSUE TITLE
Cannot read property length of null

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#302]
Just encoutered the following bug : 

http://metab.ucoin.io:9201/wot/certifiers-of/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU

```json
{

    "ucode": ​1002,
    "message": "Cannot read property 'length' of null"

}
```

**Comment by M5oul** [comment]
```sh
2016-01-09T15:24:13+01:00 - error: TypeError: Cannot read property 'length' of null
    at sanitize (/root/ucoin/app/lib/sanitize.js:60:31)
    at sanitize (/root/ucoin/app/lib/sanitize.js:85:31)
    at /root/ucoin/app/lib/streams/bma.js:125:20
    at next (native)
    at onFulfilled (/root/ucoin/node_modules/co/index.js:65:19)
    at process._tickCallback (node.js:368:9)
2016-01-09T15:24:13+01:00 - warn: Cannot read property 'length' of null
```
