### ISSUE TITLE
Logs stopped

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#305]
`ucoind logs` stopped:
```sh
2016-01-10T10:57:46+01:00 - info: Try with [fe80::ae22:bff:fe26:1ed6]:9201 5ocqzy
2016-01-10T10:57:46+01:00 - info: Will check that node kCzKJD (78.246.201.119:22013) is UP in 0 min...
fs.js:582
  binding.read(fd, buffer, offset, length, position, req);
          ^

Error: Offset is out of bounds
    at Error (native)
    at Object.fs.read (fs.js:582:11)
    at /root/ucoin/node_modules/always-tail/index.js:62:12
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by sbDevGit** [comment]
same error
