### ISSUE TITLE
TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin#308]
```
2016-01-12T19:02:36+01:00 - error:  TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"
    at next (/home/cgeek/.ucoin/node_modules/co/index.js:101:25)
    at onFulfilled (/home/cgeek/.ucoin/node_modules/co/index.js:69:7)
    at process._tickCallback (node.js:366:9)
2016-01-12T19:02:37+01:00 - warn: undefined
```

**Comment by c-geek** [comment]
Fixed by 2e7fce8f9582b8c8dff9e48ee66edda10dfd1815.
