### ISSUE TITLE
uCoin node crash

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#358]
My uCoin node stopped running at this error:
```fish
2016-03-12T14:35:53+01:00 - info: Matched 3 zeros 00070EB4763286A4AB22F0D4ADFE472BDC56BDED with Nonce = 59679 for block#51998
2016-03-12T14:40:31+01:00 - info: ⬇ IDTY ENYFbDaH1GwQRTSx1YbZ8TFHvJABHjTqoD6hLT9F8XAA Aria
2016-03-12T14:40:31+01:00 - info: ⬇ CERT HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk block#51998
2016-03-12T14:40:31+01:00 - error:  TypeError: Cannot read property 'medianTime' of null
    at /root/ucoin/app/lib/globalValidator.js:240:93
    at fn (/root/ucoin/node_modules/async/lib/async.js:579:34)
    at Immediate._onImmediate (/root/ucoin/node_modules/async/lib/async.js:495:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

It should be due to Wot:
```fish
2016-03-14T00:31:12+01:00 - info: Downloaded block #51998 from peer 88.174.120.187:15296 => Joiner/Active is outdistanced from WoT
```

**Comment by c-geek** [comment]
This code won't throw anymore in 0.20 since this code has been refactored from [this](https://github.com/ucoin-io/ucoin/blob/6d66e169435aaf3c02d1e508b1069e845eb89923/app/lib/globalValidator.js#L240) to [that](https://github.com/ucoin-io/ucoin/blob/246aa4ccd5aed07f01a500f2cbd2a1ac8b76ed75/app/lib/rules/global_rules.js#L624).

The basedBlock cannot be null because `getBlock` would have throw for the whole `checkCertificationIsValid` function.
