### ISSUE TITLE
Duniter fails to install using install.sh

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#375]
I can't start duniter : 

```
testnet@vps55093:/opt/testnet$ duniter sync twiced.fr 9330
2016-03-30T20:07:37+02:00 - error:  Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /opt/testnet/.ucoin/node_modules/naclb/lib/binding/Release/node-v47-linux-x64/naclb.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at new <anonymous> (/opt/testnet/.ucoin/node_modules/naclb/index.js:7:17)
    at Object.<anonymous> (/opt/testnet/.ucoin/node_modules/naclb/index.js:2:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by c-geek** [comment]
OS/distribution and architecture please?

**Comment by Insoleet** [comment]
Debian 7 64 bits

**Comment by c-geek** [comment]
The good news is: I reproduce it. The other good news is: uh, ... no, no other good news.

**Comment by Insoleet** [comment]
It looks like naclb is downloaded in binary package instead of sources and compiled locally !

**Comment by c-geek** [comment]
Yes I noticed that, I know what is the problem now and I know how to solve it :smile:

**Comment by c-geek** [comment]
Should be OK now with alpha36 fresh release!

**Comment by c-geek** [comment]
@vincentux still has the issue with alpha36
