### ISSUE TITLE
Server stop when received malformed transaction document

### ISSUE THREAD

**Issue by blavenie** [ucoin-io/ucoin#54]
From my unit test in ucoin-android-app project, i send this malformed document : 

  --------------------
  Version: 1
  Type: Transaction
  Currency: null
  Issuers:
  G2CBgZBPLe6FSFUgpx2Jf1Aqsgta6iib3vmDRA1yLiqU
  Inputs:
  0:T:1536:539CB0E60CD5F55CF1BE96F067E73BF55C052112:1.0
  Outputs:Comment: mon comments
  -------------------

And ucoind stop with error: 
/usr/lib/node_modules/ucoin/app/lib/rawer.js:175
    json.outputs.forEach(function (output) {
                 ^
TypeError: Cannot call method 'forEach' of undefined
    at TransactionParser.getTransaction [as rawerFunc] (/usr/lib/node_modules/ucoin/app/lib/rawer.js:175:18)
    at doJob (/usr/lib/node_modules/ucoin/app/lib/streams/parsers/doc/GenericParser.js:53:22)
    at TransactionParser.GenericParser._write (/usr/lib/node_modules/ucoin/app/lib/streams/parsers/doc/GenericParser.js:20:5)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at TransactionParser.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:585:24)
    at flow (_stream_readable.js:594:7)
    at _stream_readable.js:562:7
    at process._tickCallback (node.js:419:13)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: channel closed
    at process.target.send (child_process.js:406:26)
    at /usr/lib/node_modules/ucoin/app/lib/proof.js:59:23
    at fn (/usr/lib/node_modules/ucoin/node_modules/async/lib/async.js:579:34)
    at Object._onImmediate (/usr/lib/node_modules/ucoin/node_modules/async/lib/async.js:495:34)
    at processImmediate [as _immediateCallback] (timers.js:336:15)

**Comment by c-geek** [comment]
Good! I will investigate & create a unit test to catch this bug.

Thanks!
