### ISSUE TITLE
Trouble installing vucoin using Ubuntu 15.04

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin#74]
Reported by @Folatt at http://forum.ucoin.io/t/trouble-installing-vucoin-using-ubuntu-15-04/246

------------

This is the out put I get when I try to install vucoin:

    > scrypt-hash@1.1.10 install /usr/local/lib/node_modules/vucoin/node_modules/scrypt-hash
    > node-gyp rebuild
    
    make: Entering directory '/usr/local/lib/node_modules/vucoin/node_modules/scrypt-hash/build'
      CC(target) Release/obj.target/scrypt/crypto_scrypt-sse.o
      CXX(target) Release/obj.target/scrypt/node_scrypt.o
      SOLINK_MODULE(target) Release/obj.target/scrypt.node
      SOLINK_MODULE(target) Release/obj.target/scrypt.node: Finished
      COPY Release/scrypt.node
    make: Leaving directory '/usr/local/lib/node_modules/vucoin/node_modules/scrypt-hash/build'
     
    > naclb@0.1.0 install /usr/local/lib/node_modules/vucoin/node_modules/naclb
    > node-gyp rebuild
    
    make: Entering directory '/usr/local/lib/node_modules/vucoin/node_modules/naclb/build'
      CXX(target) Release/obj.target/nacl/nacl.o
    ../nacl.cc:24:19: error: ‘FunctionCallbackInfo’ does not name a type
     void Verify(const FunctionCallbackInfo<Value>& args) {
                       ^
    ../nacl.cc:24:39: error: expected ‘,’ or ‘...’ before ‘<’ token
     void Verify(const FunctionCallbackInfo<Value>& args) {
                                           ^
    ../nacl.cc: In function ‘void Verify(int)’:
    ../nacl.cc:26:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
       HandleScope scope(isolate);
                                ^
    ../nacl.cc:26:28: note: candidates are:
    In file included from /usr/include/nodejs/src/node.h:62:0,
                     from ../nacl.cc:1:
    /usr/include/nodejs/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
       HandleScope(const HandleScope&);
       ^
    /usr/include/nodejs/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
    /usr/include/nodejs/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
       HandleScope();
       ^
    /usr/include/nodejs/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
    ../nacl.cc:29:23: error: ‘args’ was not declared in this scope
       Local<Object> msg = args[0]->ToObject();
                           ^
    ../nacl.cc:46:57: error: no matching function for call to ‘v8::Boolean::New(v8::Isolate*&, bool)’
         args.GetReturnValue().Set(Boolean::New(isolate, true));
                                                             ^
    ../nacl.cc:46:57: note: candidate is:
    In file included from /usr/include/nodejs/src/node.h:62:0,
                     from ../nacl.cc:1:
    /usr/include/nodejs/deps/v8/include/v8.h:4349:17: note: static v8::Handle<v8::Boolean> v8::Boolean::New(bool)
     Handle<Boolean> Boolean::New(bool value) {
                     ^
    /usr/include/nodejs/deps/v8/include/v8.h:4349:17: note:   candidate expects 1 argument, 2 provided
    ../nacl.cc:49:58: error: no matching function for call to ‘v8::Boolean::New(v8::Isolate*&, bool)’
         args.GetReturnValue().Set(Boolean::New(isolate, false));
                                                              ^
    ../nacl.cc:49:58: note: candidate is:
    In file included from /usr/include/nodejs/src/node.h:62:0,
                     from ../nacl.cc:1:
    /usr/include/nodejs/deps/v8/include/v8.h:4349:17: note: static v8::Handle<v8::Boolean> v8::Boolean::New(bool)
     Handle<Boolean> Boolean::New(bool value) {
                     ^
    /usr/include/nodejs/deps/v8/include/v8.h:4349:17: note:   candidate expects 1 argument, 2 provided
    ../nacl.cc: At global scope:
    ../nacl.cc:58:17: error: ‘FunctionCallbackInfo’ does not name a type
     void Sign(const FunctionCallbackInfo<Value>& args) {
                     ^
    ../nacl.cc:58:37: error: expected ‘,’ or ‘...’ before ‘<’ token
     void Sign(const FunctionCallbackInfo<Value>& args) {
                                         ^
    ../nacl.cc: In function ‘void Sign(int)’:
    ../nacl.cc:60:28: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
       HandleScope scope(isolate);
                                ^
    ../nacl.cc:60:28: note: candidates are:
    In file included from /usr/include/nodejs/src/node.h:62:0,
                     from ../nacl.cc:1:
    /usr/include/nodejs/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
       HandleScope(const HandleScope&);
       ^
    /usr/include/nodejs/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
    /usr/include/nodejs/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
       HandleScope();
       ^
    /usr/include/nodejs/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
    ../nacl.cc:63:23: error: ‘args’ was not declared in this scope
       Local<Object> msg = args[0]->ToObject();
                           ^
    ../nacl.cc:80:62: error: invalid conversion from ‘v8::Isolate*’ to ‘uint32_t {aka unsigned int}’ [-fpermissive]
       Local<Value> size = Integer::NewFromUnsigned(isolate, smlen);
                                                                  ^
    In file included from /usr/include/nodejs/src/node.h:62:0,
                     from ../nacl.cc:1:
    /usr/include/nodejs/deps/v8/include/v8.h:1393:34: note: initializing argument 1 of ‘static v8::Local<v8::Integer> v8::Integer::NewFromUnsigned(uint32_t, v8::Isolate*)’
       V8EXPORT static Local<Integer> NewFromUnsigned(uint32_t value, Isolate*);
                                      ^
    ../nacl.cc:80:62: error: invalid conversion from ‘u64 {aka long long unsigned int}’ to ‘v8::Isolate*’ [-fpermissive]
       Local<Value> size = Integer::NewFromUnsigned(isolate, smlen);
                                                                  ^
    In file included from /usr/include/nodejs/src/node.h:62:0,
                     from ../nacl.cc:1:
    /usr/include/nodejs/deps/v8/include/v8.h:1393:34: note: initializing argument 2 of ‘static v8::Local<v8::Integer> v8::Integer::NewFromUnsigned(uint32_t, v8::Isolate*)’
       V8EXPORT static Local<Integer> NewFromUnsigned(uint32_t value, Isolate*);
                                      ^
    ../nacl.cc:81:65: error: no matching function for call to ‘v8::Array::New(v8::Isolate*&, int64_t)’
       Local<Object> array = Array::New(isolate, size->IntegerValue());
                                                                     ^
    ../nacl.cc:81:65: note: candidate is:
    In file included from /usr/include/nodejs/src/node.h:62:0,
                     from ../nacl.cc:1:
    /usr/include/nodejs/deps/v8/include/v8.h:1758:32: note: static v8::Local<v8::Array> v8::Array::New(int)
       V8EXPORT static Local<Array> New(int length = 0);
                                    ^
    /usr/include/nodejs/deps/v8/include/v8.h:1758:32: note:   candidate expects 1 argument, 2 provided
    ../nacl.cc:84:58: error: invalid conversion from ‘v8::Isolate*’ to ‘uint32_t {aka unsigned int}’ [-fpermissive]
         array->Set(i, Integer::NewFromUnsigned(isolate, sm[i]));
                                                              ^
    In file included from /usr/include/nodejs/src/node.h:62:0,
                     from ../nacl.cc:1:
    /usr/include/nodejs/deps/v8/include/v8.h:1393:34: note: initializing argument 1 of ‘static v8::Local<v8::Integer> v8::Integer::NewFromUnsigned(uint32_t, v8::Isolate*)’
       V8EXPORT static Local<Integer> NewFromUnsigned(uint32_t value, Isolate*);
                                      ^
    ../nacl.cc:84:57: error: invalid conversion from ‘u8 {aka unsigned char}’ to ‘v8::Isolate*’ [-fpermissive]
         array->Set(i, Integer::NewFromUnsigned(isolate, sm[i]));
                                                             ^
    In file included from /usr/include/nodejs/src/node.h:62:0,
                     from ../nacl.cc:1:
    /usr/include/nodejs/deps/v8/include/v8.h:1393:34: note: initializing argument 2 of ‘static v8::Local<v8::Integer> v8::Integer::NewFromUnsigned(uint32_t, v8::Isolate*)’
       V8EXPORT static Local<Integer> NewFromUnsigned(uint32_t value, Isolate*);
                                      ^
    ../nacl.cc: In function ‘void Init(v8::Handle<v8::Object>)’:
    ../nacl.cc:91:44: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [7], void (&)(int))’
       NODE_SET_METHOD(exports, "verify", Verify);
                                                ^
    ../nacl.cc:91:44: note: candidate is:
    In file included from ../nacl.cc:1:0:
    /usr/include/nodejs/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
     void SetMethod(target_t obj, const char* name,
          ^
    /usr/include/nodejs/src/node.h:112:6: note:   template argument deduction/substitution failed:
    ../nacl.cc:91:44: note:   cannot convert ‘Verify’ (type ‘void(int)’) to type ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’
       NODE_SET_METHOD(exports, "verify", Verify);
                                                ^
    ../nacl.cc:92:42: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [5], void (&)(int))’
       NODE_SET_METHOD(exports, "sign", Verify);
                                              ^
    ../nacl.cc:92:42: note: candidate is:
    In file included from ../nacl.cc:1:0:
    /usr/include/nodejs/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
     void SetMethod(target_t obj, const char* name,
          ^
    /usr/include/nodejs/src/node.h:112:6: note:   template argument deduction/substitution failed:
    ../nacl.cc:92:42: note:   cannot convert ‘Verify’ (type ‘void(int)’) to type ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’
       NODE_SET_METHOD(exports, "sign", Verify);
                                              ^
    nacl.target.mk:84: recipe for target 'Release/obj.target/nacl/nacl.o' failed
    make: *** [Release/obj.target/nacl/nacl.o] Error 1
    make: Leaving directory '/usr/local/lib/node_modules/vucoin/node_modules/naclb/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
    gyp ERR! System Linux 3.19.0-16-generic
    gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
    gyp ERR! cwd /usr/local/lib/node_modules/vucoin/node_modules/naclb
    gyp ERR! node -v v0.10.25
    gyp ERR! node-gyp -v v0.12.2
    gyp ERR! not ok 
    npm WARN This failure might be due to the use of legacy binary "node"
    npm WARN For further explanations, please read
    /usr/share/doc/nodejs/README.Debian
     
    npm ERR! naclb@0.1.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the naclb@0.1.0 install script.
    npm ERR! This is most likely a problem with the naclb package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls naclb
    npm ERR! There is likely additional logging output above.
    
    npm ERR! System Linux 3.19.0-16-generic
    npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--unsafe-perm" "-g" "vucoin"
    npm ERR! cwd /home/rogier/Downloads/cutecoin 0.9.2
    npm ERR! node -v v0.10.25
    npm ERR! npm -v 1.4.21
    npm ERR! code ELIFECYCLE
    npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/vucoin/node_modules/inquirer/node_modules/cli-color/node_modules/es5-ext/string/#/normalize/_data.js'
    npm ERR! If you need help, you may report this *entire* log,
    npm ERR! including the npm and node versions, at:
    npm ERR!     <http://github.com/npm/npm/issues>
    
    npm ERR! System Linux 3.19.0-16-generic
    npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--unsafe-perm" "-g" "vucoin"
    npm ERR! cwd /home/rogier/Downloads/cutecoin 0.9.2
    npm ERR! node -v v0.10.25
    npm ERR! npm -v 1.4.21
    npm ERR! path /usr/local/lib/node_modules/vucoin/node_modules/inquirer/node_modules/cli-color/node_modules/es5-ext/string/#/normalize/_data.js
    npm ERR! fstream_path /usr/local/lib/node_modules/vucoin/node_modules/inquirer/node_modules/cli-color/node_modules/es5-ext/string/#/normalize/_data.js
    npm ERR! fstream_type File
    npm ERR! fstream_class FileWriter
    npm ERR! code ENOENT
    npm ERR! errno 34
    npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
    npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
    npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/vucoin/node_modules/moment/min/tests.js'
    npm ERR! If you need help, you may report this *entire* log,
    npm ERR! including the npm and node versions, at:
    npm ERR!     <http://github.com/npm/npm/issues>
    
    npm ERR! System Linux 3.19.0-16-generic
    npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--unsafe-perm" "-g" "vucoin"
    npm ERR! cwd /home/rogier/Downloads/cutecoin 0.9.2
    npm ERR! node -v v0.10.25
    npm ERR! npm -v 1.4.21
    npm ERR! path /usr/local/lib/node_modules/vucoin/node_modules/moment/min/tests.js
    npm ERR! fstream_path /usr/local/lib/node_modules/vucoin/node_modules/moment/min/tests.js
    npm ERR! fstream_type File
    npm ERR! fstream_class FileWriter
    npm ERR! code ENOENT
    npm ERR! errno 34
    npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
    npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/rogier/Downloads/cutecoin 0.9.2/npm-debug.log
    npm ERR! not ok code 0

**Comment by c-geek** [comment]
Fixed since 5b52258.
