### ISSUE TITLE
Node returns 400 when block not found

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/ucoin#89]
>DEBUG:connectionpool:"GET /blockchain/block/15707 HTTP/1.1" 400 15
Traceback (most recent call last):
  File "/home/inso/code/ucoin/cutecoin/src/cutecoin/core/community.py", line 262, in monetary_mass
    req_args={'number': block_number})
  File "/home/inso/code/ucoin/cutecoin/src/cutecoin/core/community.py", line 397, in request
    return self._cache.request(request, req_args, get_args)
  File "/home/inso/code/ucoin/cutecoin/src/cutecoin/core/community.py", line 89, in request
    cached=False)
  File "/home/inso/code/ucoin/cutecoin/src/cutecoin/core/community.py", line 403, in request
    data = req.get(**get_args)
  File "/home/inso/code/ucoin/cutecoin/lib/ucoinpy/api/bma/__init__.py", line 81, in get
    return self.__get__(**kwargs)
  File "/home/inso/code/ucoin/cutecoin/lib/ucoinpy/api/bma/blockchain/__init__.py", line 69, in __get__
    return self.requests_get('/block/%d' % self.number, **kwargs).json()
  File "/home/inso/code/ucoin/cutecoin/lib/ucoinpy/api/bma/__init__.py", line 116, in requests_get
    raise ValueError('status code != 200 => %d (%s)' % (response.status_code, response.text))
ValueError: status code != 200 => 400 (Block not found)

Shouldn't the error code be 404 ?

Or maybe this is logical... 404 = no block, 400 = block doesn't exists ?

**Comment by c-geek** [comment]
404 is better.
