### ISSUE TITLE
Install failed on Debian Jessie ARM

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/ucoin#93]
I have try install uCoin node on a Debian Jessie ARM with a Linux kernel 4.0 following a way different than [the tutorial for Ubuntu](https://github.com/ucoin-io/ucoin/wiki/Install-uCoin-node#1-requirements):
```bash
apt-get install nodejs
npm install -g npm
apt-get install node-gyp
```
Versions are:
```bash
node:     0.10.38
npm:      2.10.1
node-gyp: 0.12.2
```
Logs end for uCoin node install runs as root:
```bash
> scrypt@3.0.1 install /usr/lib/node_modules/ucoin/node_modules/scrypt
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.38"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/ucoin/node_modules/scrypt/.node-gyp"
make: Entering directory '/usr/lib/node_modules/ucoin/node_modules/scrypt/build'
  CC(target) Release/obj.target/scrypt_wrapper/src/util/salt.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  AR(target) Release/obj.target/scrypt_wrapper.a
  COPY Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o
../scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.c:34:23: fatal error: emmintrin.h: No such file or directory
 #include <emmintrin.h>
                       ^
compilation terminated.
scrypt_lib.target.mk:95: recipe for target 'Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o' failed
make: *** [Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o] Error 1
make: Leaving directory '/usr/lib/node_modules/ucoin/node_modules/scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.0.3-cubietruck
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/ucoin/node_modules/scrypt
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

> vucoin@0.23.8 postinstall /usr/lib/node_modules/ucoin/node_modules/vucoin
> ./postinstall.sh

npm ERR! Linux 4.0.3-cubietruck
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "ucoin"
npm ERR! node v0.10.38
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! scrypt@3.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@3.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

The issue could come from `scrypt`.

**Comment by c-geek** [comment]
Probably same problem as #75.

**Comment by c-geek** [comment]
@M5oul: may you try installation again? It seems to build now (see #75).

**Comment by M5oul** [comment]
I can't try wright now, we could assume it's ok.

**Comment by c-geek** [comment]
Ok, feel free to reopen the issue if needed.

**Comment by M5oul** [comment]
I have tested it on my ARM board. It works well!!! Thanks.

**Comment by c-geek** [comment]
Very good news! Thanks a lot ;)
